---
- hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

- hosts: all
  roles:
    - common

- hosts: laptops,desktops
  roles:
    - dev
    - productivity

- hosts: desktops
  roles:
    - remote

- hosts: servers
  become: true
  roles:
    - remote
    - geerlingguy.docker
    - k3s.orchestration.k3s_server
  vars:
    docker_users:
      - "workstation"
    k3s_version: "v1.33.4+k3s1"

- hosts: vms
  roles:
    - remote
    - monitoring

- hosts: nas
  roles:
    - truenas