---
- hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

- hosts: all
  roles:
    - common

- hosts: laptops,desktops
  roles:
    - dev

- hosts: laptops
  roles:
    - virtualization
    - containers

- hosts: desktops
  roles:
    - remote

- hosts: servers
  become: true  
  roles:
    - monitoring

- hosts: vms
  roles:
    - containers
    - remote
    - monitoring