---
# tasks to complete before running roles
- hosts: localhost
  tags: always
  become: true
#  connection: local
  pre_tasks:
    - name: pre-run | update apt cache
      tags: always
      apt: update_cache=yes
      changed_when: False

# run roles
- hosts: localhost
  tags: root_user
  become: true
  #  become_user: workstation
  #  connection: local
#  become: true
  roles:
    - root_user
    - geerlingguy.docker

  vars:
    docker_users:
      - "workstation"

#    - role: workstation
#      become: yes
#      become_user: workstation

#- hosts: workstation
#  tags: workstation
#  become: true
#  connection: local
#  roles:
#    - workstation