---
# tasks to complete before running roles
- hosts: localhost
  tags: always
  become: true
  #  connection: local
  pre_tasks:
    - name: pre-run | update apt cache
      tags: always
      apt: update_cache=yes
      changed_when: False

# run roles
- hosts: localhost
  tags: root_user
  become: true
  roles:
    - root_user
    - geerlingguy.docker

  vars:
    docker_users:
      - "workstation"

- hosts: vm
  become: true
  roles: k3s-io.k3s-ansible.k3s-server
