persistence:
  config:
    ephemeralWritableConfigYaml: true

# values.yaml
config: |
  mqtt:
    enabled: False

  cameras:
    cam1:
      ffmpeg:
        inputs:
          - path: rtsp://XXXXXXXX:XXXXXXXX@192.168.X.X:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - detect
