---
- name: Download and install Helm GPG key
  ansible.builtin.shell: |
    curl -fsSL https://baltocdn.com/helm/signing.asc | gpg --dearmor -o /usr/share/keyrings/helm.gpg
  args:
    creates: /usr/share/keyrings/helm.gpg

- name: Add Helm apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm
    update_cache: yes

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present

- name: Install k9s
  ansible.builtin.apt:
    deb: "https://github.com/derailed/k9s/releases/download/v0.50.9/k9s_linux_amd64.deb"
    state: present
