- name: users | jay | create .ssh directory
  tags: dotfiles,jay,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: jay
    group: jay
    mode: 0700
  with_items:
    - { dir: '/home/jay/.ssh' }

- name: users | jay | copy dotfiles
  tags: dotfiles,users,jay,tmux,users,vim,zsh
  copy:
    src: users/workstation/{{ item.src }}
    dest: /home/workstation/{{ item.dest }}
    owner: workstation
    group: workstation
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'vim/vimrc', dest: '.vimrc' }
