# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- import_tasks: software/packages_utilities.yml
- import_tasks: software/development-packages.yml
- import_tasks: software/resource-monitoring.yml
- import_tasks: software/vim.yml
- import_tasks: software/jdk.yml
- import_tasks: software/pythonic.yml
- import_tasks: software/misc-packages.yml
  #- import_tasks: software/solaar.yml



