- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - neofetch
      - net-tools
      - nmap
      - ranger
      - rsync
      - sshfs
      - traceroute
      - "{{ vim_package }}"
      - wget
      - whois
      - zsh
