- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: present
    name:
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - neofetch
      - net-tools
      - nmap
      - rsync
      - traceroute
      - "{{ vim_package }}"
      - wget
      - whois
      - build-essential
      - dkms
      - "linux-headers-{{ ansible_kernel }}"