---



- name: Ensure common packages are installed
  package:
    name:
      - curl
      - wget
      - vim
      - htop
      - git
      - unzip
      - apt-transport-https
    state: present
  become: true