# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    - import_tasks: users/workstation.yml

      # Set up the ansible environment
      #  - import_tasks: ansible_setup.yml
      #
      #  # install software
      #  - import_tasks: software/repositories.yml
      #  - import_tasks: software/packages_development.yml
      #  - import_tasks: software/packages_pip.yml
      #  - import_tasks: software/packages_utilities.yml

      #  rescue:
      #    - set_fact: task_failed=true
      become: true
      become_user: workstation