- name: Check if Ollama is installed
  stat:
    path: /opt/ollama
  register: is_ollama_installed_register

- name: Download and extract Ollama if not installed
  ansible.builtin.shell:
    cmd: 'mkdir -p /opt/ollama && curl -L "https://github.com/ollama/ollama/releases/download/v0.9.2/ollama-linux-amd64.tgz" --output - | tar -xv --overwrite -z -C /opt/ollama && ln -s /opt/ollama/bin/ollama /usr/local/bin/ollama'
  when: not is_ollama_installed_register.stat.exists

- name: Create Ollama systemd service file
  ansible.builtin.copy:
    dest: "/etc/systemd/system/ollama.service"
    content: |
      [Unit]
      Description=Ollama Service
      After=network-online.target

      [Service]
      Environment="OLLAMA_DEBUG=1"
      Environment="OLLAMA_HOST=0.0.0.0"
      User=workstation
      Group=workstation
      ExecStart=/opt/ollama/bin/ollama serve
      Restart=always
      RestartSec=3

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Ollama service
  ansible.builtin.systemd:
    name: ollama.service
    enabled: yes
    state: started
    daemon_reload: yes
