- name: amd-gpu
  tags: amd-gpu
  package:
    state: present
    name:
      - rickslab-gpu-utils
      - radeontop
      - nvtop
      - python3-cairo-dev # radeontop dep
      - python3-cairo # radeontop dep
      - python3-gi-cairo # radeontop dep
      - firmware-linux
      - firmware-linux-nonfree
      - firmware-linux-free
      - firmware-amd-graphics
      - firmware-misc-nonfree
      - libgl1-mesa-dri
      - libglx-mesa0
      - mesa-vulkan-drivers
      - xserver-xorg-video-all
      - libdrm-amdgpu1
      - clinfo