- name: development packages
  tags: devel
  package:
    state: present
    name:
      - git
      - build-essential
      - dkms
      - dnsutils
      - wireshark
      - pandoc
      - texlive
      - freerdp2-x11
      - remmina
      - nodejs
      - npm

#      - https://rtyley.github.io/bfg-repo-cleaner/ add the steps

#Install draw.io package
