- name: system setup | development packages | install packages
  tags: dev,development,packages,python
  package:
    name:
      - git
      - build-essential
      - dkms
      - dnsutils
      - wireshark
      - pandoc
      - texlive
      - freerdp2-x11
      - remmina
#      - https://rtyley.github.io/bfg-repo-cleaner/ add the steps

    state: present


    #Install draw.io package
