- name: software | google-chrome | add repository
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present
  register: chrome_repo
  when: ansible_distribution in ["Debian"]

- name: software | google-chrome | update sources (repo added or changed)
  apt:
    update_cache: yes
  changed_when: False
  when: chrome_repo.changed

- name: software | google-chrome | install package
  apt:
    name: google-chrome-stable
  when: ansible_distribution in ["Debian"]
