- name: init
  tags: init
  package:
    state: present
    name:
      - git
      - build-essential
      - linux-headers-amd64
      - linux-image-amd64
      - dkms
      - flatpak
      - apt-rdepends
      - apt-file
      - apt-transport-https
      - firmware-linux
      - firmware-linux-nonfree
      - firmware-linux-free
      - bash-completion 
      - gnupg
      - curl
      - wget2
      - wget
      - lsb-release
      - ca-certificates
          #       - awk
          # - grep
          # - sed
          # - tar

      #       - rickslab-gpu-utils
      # - libgl1-mesa-dri
      # - libglx-mesa0
      # - xserver-xorg-video-all
      # - libdrm-amdgpu1
      # - clinfo
      # - ocl-icd-libopencl1
# Add step for this when flatpak is installed
# flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
