# syslog
# Aug  8 18:24:35 nuc firefox-bin[5073]: Failed to load module "xapp-gtk3-module"
# https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module
- name: issues | firefox
  tags: issues
  package:
    state: present
    name:
      - gir1.2-xapp-1.0
      - libxapp1
      - xapps-common
      - xapp



# ~/.config/plasma-workspace/env/
# export QML_XHR_ALLOW_FILE_READ=1 # solves a problem in kde, errors in syslog