# Refer https://medium.com/@daeseok.youn/prepare-the-environment-for-developing-linux-kernel-with-qemu-c55e37ba8ade
- name: system setup | kernel development | install packages
  tags: kernel-development
  package:
    name:
      - build-essential
#      - kernel-package
      - fakeroot
      - libncurses5-dev
      - libssl-dev
      - ccache
      - bison
      - libelf-dev
      - git
      - make-doc
      - make
      - bison-doc
      - bison
      - cmake
      - cmake-doc
      - libssl-dev
      - flex
      - flex-doc
      - ncurses-dev
    state: present

