- name: system setup | utilities | install utility packages
  tags: package-utilities
  package:
    state: present
    name:
      - colordiff
      - curl
      - lsof
      - net-tools
      - nmap
      - rsync
      - traceroute
      - wget
      - whois
      - dkms
      - tree
      - rfkill
      - mesa-utils
      - oomd # very important . OOM killer in user space
      - gnome-disk-utility
      - locate
#      - wireles-tools
#      - - "{{ dns_utils_package}}"