- name: system setup | development packages | install packages
  tags: dev,development,packages,python
  package:
    name:
      - git
      - python3-setuptools
      - python-pip
      - build-essential
    state: present
