# TODO https://github.com/d4nj1/TLPUI/wiki/Install-instructions#ubuntudebian-family
# FYI https://linrunner.de/tlp/faq/powertop.html
- name: power-management
  tags: power,battery
  package:
    name:
#      - tlp # sudo systemctl status tlp; sudo tlp-stat -s
#      - tlp-rdw
      - powertop
      - linux-cpupower
#      - cpupower-gui # download this manually if not available. V imp
      - cpufrequtils
      - powerstat
      - acpi
      - upower
      - gnome-power-manager
    state: present

# https://github.com/frankenfruity/plasma-pstate # install this anyhow
# watch -n 1 cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor