- name: productivity
  tags: productivity
  package:
    name:
      - yakuake
      - byobu
      - flameshot
      - plasma-browser-integration
    state: present

- name: Install the spotify flatpak
  community.general.flatpak:
    name:  io.github.Qalculate
    state: present