- name: productivity
  tags: productivity
  package:
    name:
      - yakuake
      - byobu #byobu-enable and byobu-enable-prompt after that. Check .bashrc and .profile after that
      - hollywood
      - flameshot #https://github.com/flameshot-org/flameshot#keyboard-shortcuts #do configure shortcuts - import file
      - plasma-browser-integration
      - scrcpy
      - thunderbird
      - shellcheck
      - bash-completion
      - xapp # joplin requirement
    state: present

#  https://github.com/chubin/cheat.sh#installation
# curl -s https://cht.sh/:cht.sh | sudo tee /usr/local/bin/cht.sh && sudo chmod +x /usr/local/bin/cht.sh
- name: Calculator
  tags: productivity
  community.general.flatpak:
    name: io.github.Qalculate
    state: present
#skreen-1.0.11.AppImage

# JOPLING INSTALLATION
# wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
