- name: productivity
  tags: productivity
  package:
    name:
      - yakuake
      - byobu
      - hollywood
      - flameshot
      - plasma-browser-integration
      - scrcpy
      - thunderbird
      - shellcheck
    state: present

- name: Install the spotify flatpak
  community.general.flatpak:
    name: io.github.Qalculate
    state: present
#skreen-1.0.11.AppImage