- name: resource monitoring
  tags: monitoring
  package:
    state: present
    name:
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - neofetch
      - intel-gpu-tools
      - iftop
      - nethogs
      - sysstat
      - vnstat
      - procps