- name: resource monitoring
  tags: monitoring
  package:
    state: present
    name:
      - htop
      - nvtop # GPU monitoring #https://github.com/Syllo/nvtop
      - iotop
      - "{{ lm_sensors_package }}" # run  after install sudo sensors-detect
      - neofetch
      - screenfetch
      - intel-gpu-tools #provides intel_gpu_top
      - iftop
      - nethogs #per application network usage
      - sysstat
      - vnstat
      - procps
      - lshw #system information
      - iptraf
      - glances #Amazing full screen.
      - hardinfo # very detailed
      - monitorix #historical webui
      - iperf3
      - cbm
      - nload
      - bwm-ng
#      - atop #learn this very good. not available anymore in debian testing repos
      - lshw-gtk
      - cpu-checker
      - conky #overlay, not very good
      - ncdu #storage analyzer
      - nmon
      - btop
      - rsyslog
#      - fancontrol # Doesn't work on x1c
# dont add nvidia-smi in this file because it installs nvidia driver as well