- name: virtualization 
  tags: virtualization
  package:
    name:
      - qemu-utils
      - qemu-system-x86
      - qemu-system-gui
      - libvirt-daemon-system 
      - libvirt-clients
      - virt-manager
      - libvirt0
    state: present


