- name: virtualization base
  tags: virtualization
  package:
    name:
      - libvirt-daemon-system
      - libvirt-clients
      - virt-manager
      - libvirt0
    state: present
# - name: virtualization for non-server
#   tags: virtualization
#   package:
#     name:
#       - qemu-utils
#       - qemu-system-x86
#       - qemu-system-gui
#     state: present

# - name: virtualization for server
#   hosts:
#     - all
#   tasks:
#     - name: Download Proxmox release public key with check (sha512)
#       ansible.builtin.get_url:
#         url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
#         dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
#         checksum: sha512:7da6fe34168adc6e479327ba517796d4702fa2f8b4f0a9833f5ea6e6b48f6507a6da403a274fe201595edc86a84463d50383d07f64bdde2e3658108db7d6dc87
#         mode: "0444"

#     - name: Add source Proxmox repository into sources list
#       ansible.builtin.apt_repository:
#         repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
#         state: "present"

#     - name: Update apt cache
#       apt:
#         update_cache: yes

#     - name: Installing Proxmox Kernel
#       apt:
#         pkg:
#           - proxmox-default-kernel
#           - proxmox-default-headers
#         state: present

# - name: Installing Proxmox Kernel
#   apt:
#     pkg:
#       - proxmox-ve
#       - postfix
#       - open-iscsi
#       - chrony
#     state: present
